// Code generated by protoc-gen-mcp. DO NOT EDIT.
// source: proto/exec_mcp.proto

package execmcpv1

import (
	context "context"
	errors "errors"
	mcpruntime "github.com/easyp-tech/protoc-gen-mcp/mcpruntime"
	mcp "github.com/modelcontextprotocol/go-sdk/mcp"
	proto "google.golang.org/protobuf/proto"
)

// ExecMcpAPIToolHandler defines the business logic required by generated MCP tools.
type ExecMcpAPIToolHandler interface {
	ExecProcess(ctx context.Context, req *ExecProcessRequest) (*ExecProcessResponse, error)
	RunCommand(ctx context.Context, req *RunCommandRequest) (*RunCommandResponse, error)
	StopProcess(ctx context.Context, req *StopProcessRequest) (*StopProcessResponse, error)
}

// RegisterExecMcpAPITools registers generated MCP tools for ExecMcpAPI.
func RegisterExecMcpAPITools(server *mcp.Server, impl ExecMcpAPIToolHandler, opts ...mcpruntime.RegisterOption) error {
	if impl == nil {
		return errors.New("RegisterExecMcpAPITools: impl is nil")
	}
	if err := mcpruntime.RegisterProtoTool(server, mcpruntime.ToolSpec[*ExecProcessRequest, *ExecProcessResponse]{
		Name:             "exec_process",
		Title:            "Execute Process",
		Description:      "Execute a process and return its PID for later management (background execution).",
		Namespace:        "",
		InputSchemaJSON:  ExecMcpAPI_ExecProcess_ToolSpecInputSchemaJSON,
		OutputSchemaJSON: ExecMcpAPI_ExecProcess_ToolSpecOutputSchemaJSON,
		Annotations:      &mcp.ToolAnnotations{DestructiveHint: proto.Bool(false)},
		Icons:            nil,
		NewRequest:       func() *ExecProcessRequest { return &ExecProcessRequest{} },
		NewResponse:      func() *ExecProcessResponse { return &ExecProcessResponse{} },
		Handler:          impl.ExecProcess,
	}, opts...); err != nil {
		return err
	}
	if err := mcpruntime.RegisterProtoTool(server, mcpruntime.ToolSpec[*RunCommandRequest, *RunCommandResponse]{
		Name:             "run_command",
		Title:            "Run Command",
		Description:      "Execute a command and return its output immediately (synchronous execution).",
		Namespace:        "",
		InputSchemaJSON:  ExecMcpAPI_RunCommand_ToolSpecInputSchemaJSON,
		OutputSchemaJSON: ExecMcpAPI_RunCommand_ToolSpecOutputSchemaJSON,
		Annotations:      &mcp.ToolAnnotations{DestructiveHint: proto.Bool(false)},
		Icons:            nil,
		NewRequest:       func() *RunCommandRequest { return &RunCommandRequest{} },
		NewResponse:      func() *RunCommandResponse { return &RunCommandResponse{} },
		Handler:          impl.RunCommand,
	}, opts...); err != nil {
		return err
	}
	if err := mcpruntime.RegisterProtoTool(server, mcpruntime.ToolSpec[*StopProcessRequest, *StopProcessResponse]{
		Name:             "stop_process",
		Title:            "Stop Process",
		Description:      "Stop a process by its PID using SIGTERM or SIGKILL.",
		Namespace:        "",
		InputSchemaJSON:  ExecMcpAPI_StopProcess_ToolSpecInputSchemaJSON,
		OutputSchemaJSON: ExecMcpAPI_StopProcess_ToolSpecOutputSchemaJSON,
		Annotations:      &mcp.ToolAnnotations{DestructiveHint: proto.Bool(true)},
		Icons:            nil,
		NewRequest:       func() *StopProcessRequest { return &StopProcessRequest{} },
		NewResponse:      func() *StopProcessResponse { return &StopProcessResponse{} },
		Handler:          impl.StopProcess,
	}, opts...); err != nil {
		return err
	}
	return nil
}

const ExecMcpAPI_ExecProcess_ToolSpecInputSchemaJSON = "{\"type\":\"object\",\"properties\":{\"args\":{\"type\":[\"array\",\"null\"],\"items\":{\"type\":\"string\",\"description\":\"Command line arguments.\",\"examples\":[\"example\"]},\"description\":\"Command line arguments.\",\"examples\":[[\"example\"]]},\"command\":{\"type\":\"string\",\"description\":\"The command to execute.\",\"examples\":[\"example\"],\"minLength\":1},\"dir\":{\"type\":[\"string\",\"null\"],\"description\":\"Working directory for the process.\",\"examples\":[\"example\"]},\"env\":{\"type\":[\"array\",\"null\"],\"items\":{\"type\":\"string\",\"description\":\"Environment variables in KEY=VALUE format.\",\"examples\":[\"example\"]},\"description\":\"Environment variables in KEY=VALUE format.\",\"examples\":[[\"example\"]]}},\"description\":\"ExecProcessRequest holds parameters for starting a background process.\",\"examples\":[{\"args\":[\"example\"],\"command\":\"example\",\"dir\":\"example\",\"env\":[\"example\"]}],\"required\":[\"command\"],\"additionalProperties\":false}"

const ExecMcpAPI_ExecProcess_ToolSpecOutputSchemaJSON = "{\"type\":\"object\",\"properties\":{\"args\":{\"type\":[\"array\",\"null\"],\"items\":{\"type\":\"string\",\"examples\":[\"example\"]},\"examples\":[[\"example\"]]},\"command\":{\"type\":\"string\",\"examples\":[\"example\"]},\"pid\":{\"type\":\"integer\",\"examples\":[-1]},\"startTime\":{\"type\":\"string\",\"examples\":[\"2026-03-09T10:11:12Z\"],\"format\":\"date-time\"},\"status\":{\"type\":\"string\",\"examples\":[\"example\"]}},\"description\":\"ExecProcessResponse contains information about the started process.\",\"examples\":[{\"args\":[\"example\"],\"command\":\"example\",\"pid\":-1,\"startTime\":\"2026-03-09T10:11:12Z\",\"status\":\"example\"}],\"required\":[\"pid\",\"command\",\"startTime\",\"status\"],\"additionalProperties\":false}"

const ExecMcpAPI_RunCommand_ToolSpecInputSchemaJSON = "{\"type\":\"object\",\"properties\":{\"args\":{\"type\":[\"array\",\"null\"],\"items\":{\"type\":\"string\",\"description\":\"Command line arguments.\",\"examples\":[\"example\"]},\"description\":\"Command line arguments.\",\"examples\":[[\"example\"]]},\"command\":{\"type\":\"string\",\"description\":\"The command to execute.\",\"examples\":[\"example\"],\"minLength\":1},\"dir\":{\"type\":[\"string\",\"null\"],\"description\":\"Working directory for the process.\",\"examples\":[\"example\"]},\"env\":{\"type\":[\"array\",\"null\"],\"items\":{\"type\":\"string\",\"description\":\"Environment variables in KEY=VALUE format.\",\"examples\":[\"example\"]},\"description\":\"Environment variables in KEY=VALUE format.\",\"examples\":[[\"example\"]]},\"timeout\":{\"type\":[\"integer\",\"null\"],\"description\":\"Timeout in seconds. Zero or absent means no timeout.\",\"examples\":[-1],\"minimum\":0}},\"description\":\"RunCommandRequest holds parameters for synchronous command execution.\",\"examples\":[{\"args\":[\"example\"],\"command\":\"example\",\"dir\":\"example\",\"env\":[\"example\"],\"timeout\":-1}],\"required\":[\"command\"],\"additionalProperties\":false}"

const ExecMcpAPI_RunCommand_ToolSpecOutputSchemaJSON = "{\"type\":\"object\",\"properties\":{\"args\":{\"type\":[\"array\",\"null\"],\"items\":{\"type\":\"string\",\"examples\":[\"example\"]},\"examples\":[[\"example\"]]},\"command\":{\"type\":\"string\",\"examples\":[\"example\"]},\"durationSeconds\":{\"examples\":[1.25,\"NaN\"],\"anyOf\":[{\"type\":\"number\"},{\"type\":\"string\",\"enum\":[\"NaN\",\"Infinity\",\"-Infinity\"]}]},\"executedAt\":{\"type\":\"string\",\"examples\":[\"2026-03-09T10:11:12Z\"],\"format\":\"date-time\"},\"exitCode\":{\"type\":\"integer\",\"examples\":[-1]},\"stderr\":{\"type\":\"string\",\"examples\":[\"example\"]},\"stdout\":{\"type\":\"string\",\"examples\":[\"example\"]},\"success\":{\"type\":\"boolean\",\"examples\":[true]}},\"description\":\"RunCommandResponse contains the result of synchronous command execution.\",\"examples\":[{\"args\":[\"example\"],\"command\":\"example\",\"durationSeconds\":1.25,\"executedAt\":\"2026-03-09T10:11:12Z\",\"exitCode\":-1,\"stderr\":\"example\",\"stdout\":\"example\",\"success\":true}],\"required\":[\"command\",\"exitCode\",\"stdout\",\"stderr\",\"executedAt\",\"durationSeconds\",\"success\"],\"additionalProperties\":false}"

const ExecMcpAPI_StopProcess_ToolSpecInputSchemaJSON = "{\"type\":\"object\",\"properties\":{\"kill\":{\"type\":[\"boolean\",\"null\"],\"description\":\"If true, send SIGKILL instead of SIGTERM (force kill).\",\"examples\":[true]},\"pid\":{\"type\":\"integer\",\"description\":\"The process ID to stop.\",\"examples\":[-1],\"minimum\":1}},\"description\":\"StopProcessRequest holds the parameters for stopping a process.\",\"examples\":[{\"kill\":true,\"pid\":-1}],\"required\":[\"pid\"],\"additionalProperties\":false}"

const ExecMcpAPI_StopProcess_ToolSpecOutputSchemaJSON = "{\"type\":\"object\",\"properties\":{\"pid\":{\"type\":\"integer\",\"examples\":[-1]},\"signal\":{\"type\":\"string\",\"examples\":[\"example\"]},\"status\":{\"type\":\"string\",\"examples\":[\"example\"]}},\"description\":\"StopProcessResponse confirms the signal sent to the process.\",\"examples\":[{\"pid\":-1,\"signal\":\"example\",\"status\":\"example\"}],\"required\":[\"pid\",\"signal\",\"status\"],\"additionalProperties\":false}"
