// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: proto/exec_mcp.proto

package execmcpv1

import (
	_ "github.com/easyp-tech/protoc-gen-mcp/mcp/options/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ExecProcessRequest holds parameters for starting a background process.
type ExecProcessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Args          []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	Dir           *string                `protobuf:"bytes,3,opt,name=dir,proto3,oneof" json:"dir,omitempty"`
	Env           []string               `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecProcessRequest) Reset() {
	*x = ExecProcessRequest{}
	mi := &file_proto_exec_mcp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecProcessRequest) ProtoMessage() {}

func (x *ExecProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_exec_mcp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecProcessRequest.ProtoReflect.Descriptor instead.
func (*ExecProcessRequest) Descriptor() ([]byte, []int) {
	return file_proto_exec_mcp_proto_rawDescGZIP(), []int{0}
}

func (x *ExecProcessRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ExecProcessRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ExecProcessRequest) GetDir() string {
	if x != nil && x.Dir != nil {
		return *x.Dir
	}
	return ""
}

func (x *ExecProcessRequest) GetEnv() []string {
	if x != nil {
		return x.Env
	}
	return nil
}

// ExecProcessResponse contains information about the started process.
type ExecProcessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Args          []string               `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecProcessResponse) Reset() {
	*x = ExecProcessResponse{}
	mi := &file_proto_exec_mcp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecProcessResponse) ProtoMessage() {}

func (x *ExecProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_exec_mcp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecProcessResponse.ProtoReflect.Descriptor instead.
func (*ExecProcessResponse) Descriptor() ([]byte, []int) {
	return file_proto_exec_mcp_proto_rawDescGZIP(), []int{1}
}

func (x *ExecProcessResponse) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ExecProcessResponse) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ExecProcessResponse) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ExecProcessResponse) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *ExecProcessResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// RunCommandRequest holds parameters for synchronous command execution.
type RunCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Args          []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	Dir           *string                `protobuf:"bytes,3,opt,name=dir,proto3,oneof" json:"dir,omitempty"`
	Env           []string               `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty"`
	Timeout       *int32                 `protobuf:"varint,5,opt,name=timeout,proto3,oneof" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunCommandRequest) Reset() {
	*x = RunCommandRequest{}
	mi := &file_proto_exec_mcp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCommandRequest) ProtoMessage() {}

func (x *RunCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_exec_mcp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCommandRequest.ProtoReflect.Descriptor instead.
func (*RunCommandRequest) Descriptor() ([]byte, []int) {
	return file_proto_exec_mcp_proto_rawDescGZIP(), []int{2}
}

func (x *RunCommandRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *RunCommandRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *RunCommandRequest) GetDir() string {
	if x != nil && x.Dir != nil {
		return *x.Dir
	}
	return ""
}

func (x *RunCommandRequest) GetEnv() []string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *RunCommandRequest) GetTimeout() int32 {
	if x != nil && x.Timeout != nil {
		return *x.Timeout
	}
	return 0
}

// RunCommandResponse contains the result of synchronous command execution.
type RunCommandResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Command         string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Args            []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	ExitCode        int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout          string                 `protobuf:"bytes,4,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr          string                 `protobuf:"bytes,5,opt,name=stderr,proto3" json:"stderr,omitempty"`
	ExecutedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=executed_at,json=executedAt,proto3" json:"executed_at,omitempty"`
	DurationSeconds float64                `protobuf:"fixed64,7,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	Success         bool                   `protobuf:"varint,8,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RunCommandResponse) Reset() {
	*x = RunCommandResponse{}
	mi := &file_proto_exec_mcp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCommandResponse) ProtoMessage() {}

func (x *RunCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_exec_mcp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCommandResponse.ProtoReflect.Descriptor instead.
func (*RunCommandResponse) Descriptor() ([]byte, []int) {
	return file_proto_exec_mcp_proto_rawDescGZIP(), []int{3}
}

func (x *RunCommandResponse) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *RunCommandResponse) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *RunCommandResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *RunCommandResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *RunCommandResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *RunCommandResponse) GetExecutedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExecutedAt
	}
	return nil
}

func (x *RunCommandResponse) GetDurationSeconds() float64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *RunCommandResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// StopProcessRequest holds the parameters for stopping a process.
type StopProcessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Kill          *bool                  `protobuf:"varint,2,opt,name=kill,proto3,oneof" json:"kill,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopProcessRequest) Reset() {
	*x = StopProcessRequest{}
	mi := &file_proto_exec_mcp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopProcessRequest) ProtoMessage() {}

func (x *StopProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_exec_mcp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopProcessRequest.ProtoReflect.Descriptor instead.
func (*StopProcessRequest) Descriptor() ([]byte, []int) {
	return file_proto_exec_mcp_proto_rawDescGZIP(), []int{4}
}

func (x *StopProcessRequest) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *StopProcessRequest) GetKill() bool {
	if x != nil && x.Kill != nil {
		return *x.Kill
	}
	return false
}

// StopProcessResponse confirms the signal sent to the process.
type StopProcessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Signal        string                 `protobuf:"bytes,2,opt,name=signal,proto3" json:"signal,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopProcessResponse) Reset() {
	*x = StopProcessResponse{}
	mi := &file_proto_exec_mcp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopProcessResponse) ProtoMessage() {}

func (x *StopProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_exec_mcp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopProcessResponse.ProtoReflect.Descriptor instead.
func (*StopProcessResponse) Descriptor() ([]byte, []int) {
	return file_proto_exec_mcp_proto_rawDescGZIP(), []int{5}
}

func (x *StopProcessResponse) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *StopProcessResponse) GetSignal() string {
	if x != nil {
		return x.Signal
	}
	return ""
}

func (x *StopProcessResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_exec_mcp_proto protoreflect.FileDescriptor

const file_proto_exec_mcp_proto_rawDesc = "" +
	"\n" +
	"\x14proto/exec_mcp.proto\x12\rexec_tools.v1\x1a\x1cmcp/options/v1/options.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8f\x02\n" +
	"\x12ExecProcessRequest\x129\n" +
	"\acommand\x18\x01 \x01(\tB\x1fڷ,\x1b\n" +
	"\x17The command to execute.`\x01R\acommand\x121\n" +
	"\x04args\x18\x02 \x03(\tB\x1dڷ,\x19\n" +
	"\x17Command line arguments.R\x04args\x12?\n" +
	"\x03dir\x18\x03 \x01(\tB(ڷ,$\n" +
	"\"Working directory for the process.H\x00R\x03dir\x88\x01\x01\x12B\n" +
	"\x03env\x18\x04 \x03(\tB0ڷ,,\n" +
	"*Environment variables in KEY=VALUE format.R\x03envB\x06\n" +
	"\x04_dir\"\xa8\x01\n" +
	"\x13ExecProcessResponse\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\x129\n" +
	"\n" +
	"start_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"\xff\x02\n" +
	"\x11RunCommandRequest\x129\n" +
	"\acommand\x18\x01 \x01(\tB\x1fڷ,\x1b\n" +
	"\x17The command to execute.`\x01R\acommand\x121\n" +
	"\x04args\x18\x02 \x03(\tB\x1dڷ,\x19\n" +
	"\x17Command line arguments.R\x04args\x12?\n" +
	"\x03dir\x18\x03 \x01(\tB(ڷ,$\n" +
	"\"Working directory for the process.H\x00R\x03dir\x88\x01\x01\x12B\n" +
	"\x03env\x18\x04 \x03(\tB0ڷ,,\n" +
	"*Environment variables in KEY=VALUE format.R\x03env\x12c\n" +
	"\atimeout\x18\x05 \x01(\x05BDڷ,@\n" +
	"4Timeout in seconds. Zero or absent means no timeout.\xa1\x01\x00\x00\x00\x00\x00\x00\x00\x00H\x01R\atimeout\x88\x01\x01B\x06\n" +
	"\x04_dirB\n" +
	"\n" +
	"\b_timeout\"\x91\x02\n" +
	"\x12RunCommandResponse\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x04 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x05 \x01(\tR\x06stderr\x12;\n" +
	"\vexecuted_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"executedAt\x12)\n" +
	"\x10duration_seconds\x18\a \x01(\x01R\x0fdurationSeconds\x12\x18\n" +
	"\asuccess\x18\b \x01(\bR\asuccess\"\xaf\x01\n" +
	"\x12StopProcessRequest\x129\n" +
	"\x03pid\x18\x01 \x01(\x05B'ڷ,#\n" +
	"\x17The process ID to stop.\xa1\x01\x00\x00\x00\x00\x00\x00\xf0?R\x03pid\x12U\n" +
	"\x04kill\x18\x02 \x01(\bB<ڷ,8\n" +
	"6If true, send SIGKILL instead of SIGTERM (force kill).H\x00R\x04kill\x88\x01\x01B\a\n" +
	"\x05_kill\"W\n" +
	"\x13StopProcessResponse\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x16\n" +
	"\x06signal\x18\x02 \x01(\tR\x06signal\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status2\x8a\x05\n" +
	"\n" +
	"ExecMcpAPI\x12\xd0\x01\n" +
	"\vExecProcess\x12!.exec_tools.v1.ExecProcessRequest\x1a\".exec_tools.v1.ExecProcessResponse\"zҷ,v\n" +
	"\fexec_process\x12\x0fExecute Process\x1aQExecute a process and return its PID for later management (background execution).R\x02\x10\x00\x12\xc3\x01\n" +
	"\n" +
	"RunCommand\x12 .exec_tools.v1.RunCommandRequest\x1a!.exec_tools.v1.RunCommandResponse\"pҷ,l\n" +
	"\vrun_command\x12\vRun Command\x1aLExecute a command and return its output immediately (synchronous execution).R\x02\x10\x00\x12\xaf\x01\n" +
	"\vStopProcess\x12!.exec_tools.v1.StopProcessRequest\x1a\".exec_tools.v1.StopProcessResponse\"Yҷ,U\n" +
	"\fstop_process\x12\fStop Process\x1a3Stop a process by its PID using SIGTERM or SIGKILL.R\x02\x10\x01\x1a1ʷ,-\x12+Tools for executing and managing processes.B.Z,github.com/Yakwilik/exec-mcp/proto;execmcpv1b\x06proto3"

var (
	file_proto_exec_mcp_proto_rawDescOnce sync.Once
	file_proto_exec_mcp_proto_rawDescData []byte
)

func file_proto_exec_mcp_proto_rawDescGZIP() []byte {
	file_proto_exec_mcp_proto_rawDescOnce.Do(func() {
		file_proto_exec_mcp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_exec_mcp_proto_rawDesc), len(file_proto_exec_mcp_proto_rawDesc)))
	})
	return file_proto_exec_mcp_proto_rawDescData
}

var file_proto_exec_mcp_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_exec_mcp_proto_goTypes = []any{
	(*ExecProcessRequest)(nil),    // 0: exec_tools.v1.ExecProcessRequest
	(*ExecProcessResponse)(nil),   // 1: exec_tools.v1.ExecProcessResponse
	(*RunCommandRequest)(nil),     // 2: exec_tools.v1.RunCommandRequest
	(*RunCommandResponse)(nil),    // 3: exec_tools.v1.RunCommandResponse
	(*StopProcessRequest)(nil),    // 4: exec_tools.v1.StopProcessRequest
	(*StopProcessResponse)(nil),   // 5: exec_tools.v1.StopProcessResponse
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_proto_exec_mcp_proto_depIdxs = []int32{
	6, // 0: exec_tools.v1.ExecProcessResponse.start_time:type_name -> google.protobuf.Timestamp
	6, // 1: exec_tools.v1.RunCommandResponse.executed_at:type_name -> google.protobuf.Timestamp
	0, // 2: exec_tools.v1.ExecMcpAPI.ExecProcess:input_type -> exec_tools.v1.ExecProcessRequest
	2, // 3: exec_tools.v1.ExecMcpAPI.RunCommand:input_type -> exec_tools.v1.RunCommandRequest
	4, // 4: exec_tools.v1.ExecMcpAPI.StopProcess:input_type -> exec_tools.v1.StopProcessRequest
	1, // 5: exec_tools.v1.ExecMcpAPI.ExecProcess:output_type -> exec_tools.v1.ExecProcessResponse
	3, // 6: exec_tools.v1.ExecMcpAPI.RunCommand:output_type -> exec_tools.v1.RunCommandResponse
	5, // 7: exec_tools.v1.ExecMcpAPI.StopProcess:output_type -> exec_tools.v1.StopProcessResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_exec_mcp_proto_init() }
func file_proto_exec_mcp_proto_init() {
	if File_proto_exec_mcp_proto != nil {
		return
	}
	file_proto_exec_mcp_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_exec_mcp_proto_msgTypes[2].OneofWrappers = []any{}
	file_proto_exec_mcp_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_exec_mcp_proto_rawDesc), len(file_proto_exec_mcp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_exec_mcp_proto_goTypes,
		DependencyIndexes: file_proto_exec_mcp_proto_depIdxs,
		MessageInfos:      file_proto_exec_mcp_proto_msgTypes,
	}.Build()
	File_proto_exec_mcp_proto = out.File
	file_proto_exec_mcp_proto_goTypes = nil
	file_proto_exec_mcp_proto_depIdxs = nil
}
